[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
solc_version = "0.8.24" # Atualizado para compatibilidade com OZ v5

remappings = [
    '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/'
]

[fuzz]
runs = 256
